spring.application.name=thaiaddressbatch

#Config Database
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/prototype?createDatabaseIfNotExist=true&rewriteBatchedStatements=true
spring.datasource.username=xxxxx
spring.datasource.password=xxxxx
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.main.allow-circular-references=true

# config Spring Batch create Metadata table when open app.
spring.batch.jdbc.initialize-schema=always

# \u0E2A\u0E31\u0E48\u0E07\u0E43\u0E2B\u0E49 Spring Boot \u0E23\u0E31\u0E19 Job \u0E17\u0E31\u0E49\u0E07\u0E2B\u0E21\u0E14\u0E17\u0E35\u0E48\u0E21\u0E35\u0E43\u0E19\u0E23\u0E30\u0E1A\u0E1A\u0E17\u0E31\u0E19\u0E17\u0E35\u0E40\u0E21\u0E37\u0E48\u0E2D\u0E40\u0E1B\u0E34\u0E14\u0E40\u0E04\u0E23\u0E37\u0E48\u0E2D\u0E07
spring.batch.job.enabled=true

spring.jpa.properties.hibernate.jdbc.batch_size=10
spring.jpa.properties.hibernate.order_inserts=true

address.thai.from.external.url=https://geoth.thiti.dev/api
address.thai.from.external.path.all.province=/provinces/all
address.thai.from.external.path.get.districts.by.province.id=/provinces-with-districts/
address.thai.from.external.path.get.subdistricts.by.districts.id=/districts-with-subdistricts/